//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manga()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int MangaId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string SourceImage { get; set; }
        public int Volumes { get; set; }
        public string Synopsis { get; set; }
        public string Genre { get; set; }
        public System.DateTime DateReleased { get; set; }
        public double Rating { get; set; }
        public bool Favourite { get; set; }
        public int ReadingState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
