//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string UserName { get; set; }
        public string Text { get; set; }
        public int MangaId { get; set; }
        public int Rating { get; set; }
        public System.DateTime DatePublished { get; set; }
    
        public virtual Manga Manga { get; set; }
    }
}
